language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: macisi528@gmail.com
  api_key:
    secure: fwvKxxeDS7oDPTvYw/fCFGp+eQKHRw9ZQJJ7Jr7d0lWiuLHQ7tzlbE3OeIHHWXWlykO4NdQoYDmmcyvpZIY7nE0tUIm5+v5Ittl6RBQ+6gMujupfZUWDWAyw46q20x1UyjAhT3MEZVPd999Tgy69KLUMkKvopEMzeKiJ34i8+ppCiQ9bIKEhguXN4fQ4Bprf2r5V4zvjnAE/7oe1OmbnDX7qIRBDbiS9gOY27Du8zb3/M+b5oL7s6h31QLFvcbR60/S+lEFxGCowQDnP9yG7ZfMGeZvzUkHoNDKLeTM9ktF9a9zwVMUjvAno6yEtr193LMe10pKOZRFa3noX25sRkTp+sG+/iNWbLkTKk+KxePmW28whDDjYEEQVfeJ1Aq19XWWOnSAqJ00J4Yd64i/RYLpkmu5NBhs9EpuHPQJE8JivyyGjxklqlYtIlMW5u7HDFUagGNsh3G36/+7lErLP7EbLNebvTGz1y/aZv8+rDXU50GEhsKe7bFHLp3HD/Ug+3lhMLRV2tnmpN68hh3mJ41ayq4g6jlbbKBN+lLmxmwCmxJkwUu3FWjzsWAoUQgMYSLTqcopYW4SdV1qHApVTAd/stW+1VHJxYTQ9tvtEw8K6oj6tTUELALDmSENHR/gAjnaSX8Hp4u6SfUP4T1WMhbp+DhyOEexuVZErUo8lt5A=
  on:
    tags: true
    repo: EHDFE/ehdev-configer-normal
